import 'package:dio/dio.dart';
import 'package:splash_app/core/helper/cache_helper.dart';

import 'end_point.dart';

class ApiInterceptor extends Interceptor {
  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    options.headers['Authorization'] =
        'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3ByaW1hcnlzaWQiOiI1ZTM0YmJmOC1jZWQyLTQzYzAtOWY4Ny00MDhmM2Y2YTdmYTAiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9tb2JpbGVwaG9uZSI6IjAxMDAwMDAwMDAwIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiZW5nYWhtZWRhbHNhaWVtQGdtYWlsLmNvbSIsIlR5cGUiOiJVc2VyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTczOTAzNDI1NywiaXNzIjoiQ2FyQ2FyZUlkZW50aXR5IiwiYXVkIjoiQ2FyQ2FyZVVzZXJzIn0.GEFPxisQPZASYSASOs6ODEviyiTrL29EdbYGZiTK0v0';
    super.onRequest(options, handler);
  }
}
